name: Fetch Data
on:
  schedule:
    - cron:  '40 * * * *' # every hour
  push:
    paths:
     - '.github/workflows/fetch_data.yml'
  workflow_dispatch: {}

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Fetch talk/speaker/etc. data from Pretalx
      - name: Cache Julia Packages
        uses: actions/cache@v2
        env:
          cache-name: cache-julia-pkgs
        with:
          path: ~/.julia
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Update Data
        run: |
          cd data
          julia --project -e 'import Pkg; Pkg.instantiate(); include("fetch.jl");'
          cd ..
        env:
          PRETALX_TOKEN: ${{ secrets.PRETALX_TOKEN }}

      # Commit all the changes
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: fetch data
 